nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /d/docker/opt:/opt

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - /d/docker/opt:/opt

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - /d/docker/opt/data/mysql:/var/lib/mysql
      - /d/docker/opt/logs/mysql:/var/log/mysql
    environment:
      - MYSQL_DATABASE=sw
      - MYSQL_USER=rrrr
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456

redis:
    build: ./redis
    ports:
      - "6379:6379"