version: '2'

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

services:
    nginx:
      build:
        context: ./nginx
      ports:
        - "80:80"
      links:
        - "php"
      volumes:
        - ${WORKSPACE}:/opt/
      networks:
        - backend

    php:
      build: ./php
      links:
        # 如果要使用mysql请把这句取消注释
        # - "mysql"
        # 如果要使用redis请把这句话取消注释
        # - "redis"
      volumes:
        - ${WORKSPACE}:/opt
        - ${LOGS_PATH}/php:/opt/logs/php
      networks:
        - backend
      environment:
        - PHP_IDE_CONFIG=serverName=${SERVER_NAME}
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"

    mysql:
      build: ./mysql
      ports:
        - "3306:3306"
      volumes:
        - ${DATA_PATH}/mysql:/var/lib/mysql
        - ${LOGS_PATH}/mysql:/var/log/mysql
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_PORT=${MYSQL_PORT}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      networks:
        - backend

    redis:
      build: ./redis
      ports:
        - "6379:6379"
      networks:
        - backend

